application/models/__init__.py
# -*- coding: utf-8 -*-

from model import Todo

__all__ = ['Todo']

application/models/model.py
# -*- coding: utf-8 -*-

from application.extensions import db
from datetime import datetime

__all__ = ['Todo']


class Todo(db.Model):
    """data model"""
    __tablename__ = 'todo'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    posted_on = db.Column(db.Date, default=datetime.utcnow)
    status = db.Column(db.Boolean(), default=False)

    def __init__(self, *args, **kwargs):
        super(Todo, self).__init__(*args, **kwargs)

    def __repr__(self):
        return "<Todo '%s'>" % self.title

    def store_to_db(self):
        """save to database"""

        db.session.add(self)
        db.session.commit()

    def delete_todo(self):
        """delete data"""

        db.session.delete(self)
        db.session.commit()

application/__init__.py
# -*- coding: utf-8 -*-

from app import create_app
from app import db

application/app.py
# -*- coding: utf-8 -*-

from flask import Flask
from controllers import blueprints
from configs import config
from extensions import db


def create_app(config_name=None):
    if config_name is None:
        config_name = 'default'

    app = Flask(__name__)
    app.config.from_object(config[config_name])

    # db
    db.init_app(app)

    # blueprints
    for bp in blueprints:
        app.register_blueprint(bp)

    return app

application/controllers/__init__.py
# -*- coding: utf-8 -*-

import todo

blueprints = [
    todo.todo_bp
]

application/controllers/todo.py
# -*- coding: utf-8 -*-

import flask
from flask import request, redirect, flash, render_template, url_for
from application.extensions import db
from application.models import Todo

todo_bp = flask.Blueprint(
    'todo',
    __name__,
    template_folder='../templates'
)


@todo_bp.route('/', methods=['GET', 'POST'])
def index():
    todo = Todo.query.order_by('-id')
    _form = request.form

    if request.method == 'POST':
        title = _form["title"]
        td = Todo(title=title)
        try:
            td.store_to_db()
            flash("add task successfully!")
            return redirect(url_for('todo.index'))
        except Exception as e:
            print e
            flash("fail to add task!")

    return render_template('index.html', todo=todo)


@todo_bp.route('/<int:todo_id>/del')
def del_todo(todo_id):
    todo = Todo.query.filter_by(id=todo_id).first()
    if todo:
        todo.delete_todo()
    flash("delete task successfully")
    return redirect(url_for('todo.index'))


@todo_bp.route('/<int:todo_id>/edit', methods=['GET', 'POST'])
def edit(todo_id):
    todo = Todo.query.filter_by(id=todo_id).first()

    if request.method == 'POST':
        Todo.query.filter_by(
            id=todo_id
        ).update({
            Todo.title: request.form['title']
        })
        db.session.commit()
        flash("update successfully!")
        return redirect(url_for('todo.index'))

    return render_template('edit.html', todo=todo)


@todo_bp.route('/<int:todo_id>/done')
def done(todo_id):
    todo = Todo.query.filter_by(id=todo_id).first()
    if todo:
        Todo.query.filter_by(id=todo_id).update({Todo.status: True})
        db.session.commit()
        flash("task is completed!")

    return redirect(url_for('todo.index'))


@todo_bp.route('/<int:todo_id>/redo')
def redo(todo_id):
    todo = Todo.query.filter_by(id=todo_id).first()
    if todo:
        Todo.query.filter_by(id=todo_id).update({Todo.status: False})
        flash("redo successfully!")
        db.session.commit()

    return redirect(url_for('todo.index'))


@todo_bp.errorhandler(404)
def page_not_found():
    return render_template('404.html'), 404

application/templates/base.html
<!DOCTYPE html>
<html>
    <head>
	    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	    <title>TODO Lists</title>
	    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.1.0.js') }}"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css" />
        <script type="text/javascript">
            $(document).ready(function() {
                $("#divPop").animate({
                    "opacity": "hide",
                    "width": 800,
                    "height":30
                },
                1500
                );
            });
        </script>
    </head>

    <body class="page">
        <h1> TODO Lists </h1>
        <hr>

        {% block content %} {% endblock %}
        <br />
        {% for message in get_flashed_messages() %}
          <div id="divPop" style="background-color: #f0f0f0; border: solid 1px #000000;width: 800px; height: 30px;">
              <div style="text-align:center;">
                  {{ message }}
              </div>
          </div>
        {% endfor %}

        <!-- footer -->
        <hr>
        <div id="poweredby">
        Powered by: <a href="http://flask.pocoo.org/">Flask</a>.
        </div>
        <br />
    </body>
</html>

application/templates/edit.html
{% extends "base.html" %}
{% block content %}
<h2>Update</h2>
<form method="post" action="{{ url_for('todo.edit', todo_id=todo.id)}}">
    <input id="title" name="title" placeholder="update todo item" type="text">
    <button type="submit">Update</button>
</form>
{% endblock %}

application/templates/index.html
{% extends "base.html" %}
{% block content %}

<h2>Todo</h2>
{% if todo %}
    <ol>
    {% for t in todo %}
    {% if t.status==False %}
        <li>{{ t.title|safe }} <a href="{{ url_for('todo.del_todo', todo_id=t.id) }}" >delete</a> |
            <a href="{{ url_for('todo.edit', todo_id=t.id) }}" >update </a> |
            <a href="{{ url_for('todo.done', todo_id=t.id) }}" >complete</a>
        </li>
    {% endif %}
    {% endfor %}
    </ol>
{% else %}
    <b>nothing</b>
{% endif %}

<h2>Completed</h2>
{% if todo %}
    <ol>
    {% for t in todo %}
    {% if t.status==True %}
        <li>
            <del>{{ t.title|safe }}</del>
            <a href="{{ url_for('todo.del_todo', todo_id=t.id) }}" >delete</a> |
            <a href="{{ url_for('todo.redo', todo_id=t.id) }}" >redo</a>
        </li>
    {% endif %}
    {% endfor %}
    </ol>
{% else %}
    <b>nothing</b>
{% endif %}

<h2>Add</h2>
<form method="post">
<input id="title" name="title" placeholder="add todo item" type="text">
<button type="submit">Submit</button>
</form>
<p> Ja Ja bitte du bist mein  </p>
<p> not yet </p>
<p> U O ME </p>
<p> Good for u man </p>
<p> u did it </p>
<p> good night man see ya soon </p>
{% endblock %}